// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWd5OkPr6W8iMNBQ_Nl7I4w4N9QQFBvgQ',
    appId: '1:409272897966:web:e00ca4d48164315db9f83f',
    messagingSenderId: '409272897966',
    projectId: 'prakflutterfirebase-f3cc7',
    authDomain: 'prakflutterfirebase-f3cc7.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-f3cc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI0x1NC51kJ68s_-UbOUhoEg24iQpFRLs',
    appId: '1:409272897966:android:050ff13b6259980eb9f83f',
    messagingSenderId: '409272897966',
    projectId: 'prakflutterfirebase-f3cc7',
    storageBucket: 'prakflutterfirebase-f3cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC93Q61CWWc9kpi9T5zJ44YVDUvoRwWBTE',
    appId: '1:409272897966:ios:04da634137a3ec92b9f83f',
    messagingSenderId: '409272897966',
    projectId: 'prakflutterfirebase-f3cc7',
    storageBucket: 'prakflutterfirebase-f3cc7.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC93Q61CWWc9kpi9T5zJ44YVDUvoRwWBTE',
    appId: '1:409272897966:ios:04da634137a3ec92b9f83f',
    messagingSenderId: '409272897966',
    projectId: 'prakflutterfirebase-f3cc7',
    storageBucket: 'prakflutterfirebase-f3cc7.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWd5OkPr6W8iMNBQ_Nl7I4w4N9QQFBvgQ',
    appId: '1:409272897966:web:efc11bf8394c07e8b9f83f',
    messagingSenderId: '409272897966',
    projectId: 'prakflutterfirebase-f3cc7',
    authDomain: 'prakflutterfirebase-f3cc7.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-f3cc7.appspot.com',
  );
}
